# Generated by Django 4.2 on 2023-05-07 16:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menu_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reservation_date',
            field=models.DateField(default=django.utils.timezone.now, unique_for_date='reservation_date'),
            preserve_default=False,
        ),
    ]
